[ETFE-1186] Updated to match latest prototype and copy deck design
hmrc/emcs-tfe-report-a-receipt-frontend pull request #110
Opened 2023-06-20 13:31 UTC by MJCallahanPage

2023-06-20 13:31 UTC, MJCallahanPage commented
![image](https://github.com/hmrc/emcs-tfe-report-a-receipt-frontend/assets/16954819/42f91163-d5a0-4a0f-a521-7abbb06ae533)

2023-06-22 14:49 UTC, james-work-account requested changes
I think I've found a bug, where you can submit as "Accepted but unsatisfactory" or "Partially refused" without any items. Steps to reproduce:

1. Select "unsatisfactory" or "partially refused" option on `choose-accept-movement`
2. Fill out info about an item, go through to `check-answers`
3. Remove the item from CYA, get redirected to `select-items-give-information`
4. Click "Back", stay on `select-items-give-information`
5. Click "Back" again, get redirected to CYA
6. You are on CYA without any items. Click "Submit report of receipt"
7. You are redirected to `confirmation` with the "Report of receipt submitted" text

I'm not sure why clicking "Back" twice allows you to go to CYA without any items, but it might be worth addressing here - either by implementing an error check on the Submit or by figuring out why/how-to-stop this kind of "Back" behaviour.

Content all looks good though and it passes against the JTs.

2023-06-23 09:55 UTC, MJCallahanPage commented
> I think I've found a bug, where you can submit as "Accepted but unsatisfactory" or "Partially refused" without any items. Steps to reproduce:
> 
> 1. Select "unsatisfactory" or "partially refused" option on `choose-accept-movement`
> 2. Fill out info about an item, go through to `check-answers`
> 3. Remove the item from CYA, get redirected to `select-items-give-information`
> 4. Click "Back", stay on `select-items-give-information`
> 5. Click "Back" again, get redirected to CYA
> 6. You are on CYA without any items. Click "Submit report of receipt"
> 7. You are redirected to `confirmation` with the "Report of receipt submitted" text
> 
> I'm not sure why clicking "Back" twice allows you to go to CYA without any items, but it might be worth addressing here - either by implementing an error check on the Submit or by figuring out why/how-to-stop this kind of "Back" behaviour.
> 
> Content all looks good though and it passes against the JTs.

I've pushed up a guard for this which will bounce the USer back to Select Items if there's no added items when we expect at least one. 

Long term, we need a CYA Validation story and a design to help the User fix any issues. Guiding them back through the flow.

2023-06-23 10:57 UTC, james-work-account approved these changes

2023-06-23 11:35 UTC, merged