[ETFE-1268] Update the AddedItemsController and View to render Card view for Items
hmrc/emcs-tfe-report-a-receipt-frontend pull request #128
Opened 2023-06-28 10:43 UTC by MJCallahanPage

2023-06-28 10:51 UTC, MJCallahanPage commented
https://github.com/hmrc/emcs-tfe-report-a-receipt-frontend/assets/16954819/85b135b1-3f27-4ed2-92c7-4fa3b8330378

2023-06-28 14:15 UTC, james-work-account requested changes

2023-06-28 15:07 UTC, james-work-account approved these changes

2023-07-03 09:09 UTC, james-work-account submitted a review, later dismissed

2023-07-04 11:48 UTC, james-work-account approved these changes

2023-07-04 12:05 UTC, merged