ETFE-1238: Updated error validation
hmrc/emcs-tfe-report-a-receipt-frontend pull request #155
Opened 2023-07-05 11:37 UTC by r-melvin

2023-07-05 16:10 UTC, MJCallahanPage requested changes

2023-07-05 16:10 UTC, MJCallahanPage commented on app/controllers/ItemShortageOrExcessController.scala
> +                      args = Seq(value.amount, maxAmount(idx, item, isPartiallyRefusingAnAmountOfItem))
Where it currently uses: `value.amount` this needs to change. It should be the `RefusedAmount` that is passed into this.

2023-07-05 16:10 UTC, MJCallahanPage commented on app/controllers/ItemShortageOrExcessController.scala
> +                      args = Seq(value.amount, maxAmount(idx, item, isPartiallyRefusingAnAmountOfItem))
I also wonder if the `UnitOfMeasure` needs to be passed to the view. Might be worth checking with clare, as this doesn't really make sense to me:
![image](https://github.com/hmrc/emcs-tfe-report-a-receipt-frontend/assets/16954819/f33dba20-6367-403a-90e2-a2b5cb283674)

Saying:
> "You have refused 1 litre of this item. The amount of shortage cannot be more than 0"
> "You have refused 2 litres of this item. The amount of shortage cannot be more than 0"
> "You have refused 10 kilograms of this item. The amount of shortage cannot be more than 45"
etc...

Might make more sense? 🤷

2023-07-06 14:42 UTC, MJCallahanPage requested changes

2023-07-06 16:41 UTC, r-melvin commented on app/forms/package.scala
> +  private[forms] val NUMERIC_REGEX: String = "^(([0-9]*)|(([0-9]*)\\.([0-9]*)))$" // This regex does not accept comma separated numbers e.g. 2,000,000
Probably but I couldn't make it work for a comma every 4th digit nor could I find one that worked properly online.

2023-07-07 14:24 UTC, MJCallahanPage approved these changes
LGTM 🟢 🚀

2023-07-07 15:36 UTC, merged