[ETFE-744] Add check answers item page
hmrc/emcs-tfe-report-a-receipt-frontend pull request #45
Opened 2023-03-20 16:53 UTC by james-work-account

2023-03-20 16:56 UTC, james-work-account commented on build.sbt
> +    ScoverageKeys.coverageMinimumStmtTotal := 95,
😎

2023-03-21 16:56 UTC, james-work-account commented
Wait for #46 before merging this - I'll rebase off main before opening up again once that's in

2023-03-22 09:51 UTC, stephenkward commented on app/viewmodels/checkAnswers/ShortageOrExcessItemSummary.scala
> +                value = ValueViewModel(Text(value)),
shortage or excess reason value that is displayed on the check answers item page needs to start with uppercase

2023-03-23 08:23 UTC, stephenkward requested changes
added couple of comments to PR

2023-03-23 10:17 UTC, stephenkward approved these changes

2023-03-23 10:17 UTC, merged